In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Indian FMCG Retail Sales  Customer  Inventory (2024).csv to Indian FMCG Retail Sales  Customer  Inventory (2024).csv

In [ ]:
import pandas as pd

df = pd.read_csv('/content/Indian FMCG Retail Sales  Customer  Inventory (2024).csv')

In [ ]:
df.head()

,Invoice_ID,Invoice_Date,City,Store_Format,Category,Brand,Channel,Payment_Mode,Units,Cost_Price,...,Revenue,Cost,Margin,Margin_%,Stock_On_Hand,Reorder_Level,Lead_Time_Days,Customer_Age,Customer_Gender,Loyalty_Flag
0,58018430,2024-02-02 13:50:00,Kolkata,Super,Grocery,Nestle,Online,Wallet,2,148.999035,...,350.114418,297.998070,52.116348,0.148855,154,31,11,20.0,M,1
1,48157952,2024-10-09 11:52:00,Hyderabad,Hyper,Home Care,PepsiCo,Offline,Wallet,1,80.626759,...,106.034197,80.626759,25.407438,0.239616,130,24,5,26.0,F,1
2,23283831,2024-08-26 22:03:00,Chennai,Hyper,Snacks,PepsiCo,Online,Card,5,181.233170,...,1044.900114,906.165848,138.734266,0.132773,270,44,8,27.0,F,0
3,53537460,2024-06-09 04:34:00,Bengaluru,Hyper,Beverages,Nestle,Omnichannel,Card,2,195.811402,...,521.759920,391.622805,130.137115,0.249420,403,63,8,NaN,F,0
4,55348596,2024-06-07 01:13:00,Delhi,Super,Snacks,ITC,Offline,Card,3,23.571888,...,91.873416,70.715665,21.157751,0.230292,366,40,9,60.0,F,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 21 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Invoice_ID       100000 non-null  int64
 1   Invoice_Date     100000 non-null  object
 2   City             100000 non-null  object
 3   Store_Format     100000 non-null  object
 4   Category         100000 non-null  object
 5   Brand            100000 non-null  object
 6   Channel          100000 non-null  object
 7   Payment_Mode     100000 non-null  object
 8   Units            100000 non-null  int64
 9   Cost_Price       100000 non-null  float64
 10  Selling_Price    100000 non-null  float64
 11  Revenue          100000 non-null  float64
 12  Cost             100000 non-null  float64
 13  Margin           100000 non-null  float64
 14  Margin_%         100000 non-null  float64
 15  Stock_On_Hand    100000 non-null  int64
 16  Reorder_Level    100000 non-null  int64
 17  Lead_Time_Days   100000 non-null  int64
 18  Customer_Age     59919 non-null   float64
 19  Customer_Gender  94952 non-null   object
 20  Loyalty_Flag     100000 non-null  int64
dtypes: float64(7), int64(6), object(8)
memory usage: 16.0+ MB

In [ ]:
df.isnull().sum()

Invoice_ID             0
Invoice_Date           0
City                   0
Store_Format           0
Category               0
Brand                  0
Channel                0
Payment_Mode           0
Units                  0
Cost_Price             0
Selling_Price          0
Revenue                0
Cost                   0
Margin                 0
Margin_%               0
Stock_On_Hand          0
Reorder_Level          0
Lead_Time_Days         0
Customer_Age       40081
Customer_Gender     5048
Loyalty_Flag           0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe()

,Invoice_ID,Units,Cost_Price,Selling_Price,Revenue,Cost,Margin,Margin_%,Stock_On_Hand,Reorder_Level,Lead_Time_Days,Customer_Age,Loyalty_Flag
count,1.000000e+05,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,59919.000000,100000.000000
mean,5.512347e+07,2.998290,104.859625,131.107353,393.351350,314.614493,78.736857,0.193368,274.156670,49.467710,8.516810,41.076620,0.297200
std,2.596457e+07,1.414619,54.825341,69.862379,297.154653,234.901995,74.236348,0.075143,129.853861,17.305614,3.458274,13.565069,0.457028
min,1.000120e+07,1.000000,10.000526,10.580915,10.653198,10.002024,0.556870,0.047621,50.000000,20.000000,3.000000,18.000000,0.000000
25%,3.271665e+07,2.000000,57.478508,71.327813,155.415176,125.467072,24.448402,0.131251,161.000000,34.000000,6.000000,29.000000,0.000000
50%,5.518370e+07,3.000000,104.903700,129.999158,313.349100,252.801900,53.552720,0.200287,274.000000,50.000000,9.000000,41.000000,0.000000
75%,7.751346e+07,4.000000,152.320122,188.854907,573.063568,462.376451,110.075103,0.259151,387.000000,64.000000,12.000000,53.000000,1.000000
max,9.999632e+07,5.000000,199.999659,289.699598,1443.134985,999.985219,447.207497,0.310343,499.000000,79.000000,14.000000,64.000000,1.000000

In [ ]:
df['Invoice_Date'].head()

0    2024-02-02 13:50:00
1    2024-10-09 11:52:00
2    2024-08-26 22:03:00
3    2024-06-09 04:34:00
4    2024-06-07 01:13:00
Name: Invoice_Date, dtype: object

In [ ]:
df['Invoice_Date'] = pd.to_datetime(df['Invoice_Date'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 21 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Invoice_ID       100000 non-null  int64
 1   Invoice_Date     100000 non-null  datetime64[ns]
 2   City             100000 non-null  object
 3   Store_Format     100000 non-null  object
 4   Category         100000 non-null  object
 5   Brand            100000 non-null  object
 6   Channel          100000 non-null  object
 7   Payment_Mode     100000 non-null  object
 8   Units            100000 non-null  int64
 9   Cost_Price       100000 non-null  float64
 10  Selling_Price    100000 non-null  float64
 11  Revenue          100000 non-null  float64
 12  Cost             100000 non-null  float64
 13  Margin           100000 non-null  float64
 14  Margin_%         100000 non-null  float64
 15  Stock_On_Hand    100000 non-null  int64
 16  Reorder_Level    100000 non-null  int64
 17  Lead_Time_Days   100000 non-null  int64
 18  Customer_Age     59919 non-null   float64
 19  Customer_Gender  94952 non-null   object
 20  Loyalty_Flag     100000 non-null  int64
dtypes: datetime64[ns](1), float64(7), int64(6), object(7)
memory usage: 16.0+ MB

In [ ]:
df['Customer_Gender'].value_counts(dropna=False)

Customer_Gender
M      44920
F      44905
O       5127
NaN     5048
Name: count, dtype: int64

In [ ]:
df['Customer_Gender'] = df['Customer_Gender'].fillna('Unknown')

In [ ]:
df['Customer_Gender'].value_counts(dropna=False)

Customer_Gender
M          44920
F          44905
O           5127
Unknown     5048
Name: count, dtype: int64

In [ ]:
df['Customer_Age'].describe()

count    59919.000000
mean        41.076620
std         13.565069
min         18.000000
25%         29.000000
50%         41.000000
75%         53.000000
max         64.000000
Name: Customer_Age, dtype: float64

In [ ]:
df['Customer_Age'].isnull().sum()

np.int64(40081)

In [ ]:
df['Customer_Age'].value_counts().sort_index()

Customer_Age
18.0    1271
19.0    1262
20.0    1269
21.0    1287
22.0    1240
23.0    1252
24.0    1281
25.0    1242
26.0    1210
27.0    1320
28.0    1254
29.0    1271
30.0    1291
31.0    1326
32.0    1231
33.0    1284
34.0    1236
35.0    1253
36.0    1307
37.0    1269
38.0    1328
39.0    1245
40.0    1296
41.0    1171
42.0    1302
43.0    1316
44.0    1244
45.0    1299
46.0    1288
47.0    1245
48.0    1278
49.0    1326
50.0    1259
51.0    1291
52.0    1280
53.0    1235
54.0    1269
55.0    1343
56.0    1205
57.0    1343
58.0    1288
59.0    1334
60.0    1259
61.0    1281
62.0    1250
63.0    1283
64.0    1305
Name: count, dtype: int64

In [ ]:
df['City'].value_counts()

City
Kolkata      12681
Delhi        12649
Mumbai       12492
Chennai      12467
Hyderabad    12440
Ahmedabad    12436
Bengaluru    12432
Pune         12403
Name: count, dtype: int64

In [ ]:
df['Store_Format'].value_counts()

Store_Format
Hyper      33443
Express    33314
Super      33243
Name: count, dtype: int64

In [ ]:
df['Category'].value_counts()

Category
Fruits           12708
Home Care        12630
Beverages        12585
Snacks           12514
Vegetables       12472
Grocery          12412
Personal Care    12409
Dairy            12270
Name: count, dtype: int64

In [ ]:
df['Brand'].value_counts()

Brand
ITC          12649
HUL          12572
Nestle       12560
Amul         12521
PepsiCo      12507
Britannia    12497
Tata         12461
Parle        12233
Name: count, dtype: int64

In [ ]:
df['Channel'].value_counts()

Channel
Omnichannel    33383
Offline        33362
Online         33255
Name: count, dtype: int64

In [ ]:
df['Payment_Mode'].value_counts()

Payment_Mode
UPI       25236
Card      25127
Wallet    24888
Cash      24749
Name: count, dtype: int64

In [ ]:
df['Units'].describe()

count    100000.000000
mean          2.998290
std           1.414619
min           1.000000
25%           2.000000
50%           3.000000
75%           4.000000
max           5.000000
Name: Units, dtype: float64

In [ ]:
df['Cost_Price'].describe()

count    100000.000000
mean        104.859625
std          54.825341
min          10.000526
25%          57.478508
50%         104.903700
75%         152.320122
max         199.999659
Name: Cost_Price, dtype: float64

In [ ]:
df['Selling_Price'].describe()

count    100000.000000
mean        131.107353
std          69.862379
min          10.580915
25%          71.327813
50%         129.999158
75%         188.854907
max         289.699598
Name: Selling_Price, dtype: float64

In [ ]:
df['Revenue'].describe()

count    100000.000000
mean        393.351350
std         297.154653
min          10.653198
25%         155.415176
50%         313.349100
75%         573.063568
max        1443.134985
Name: Revenue, dtype: float64

In [ ]:
(df['Revenue'] - (df['Units'] * df['Selling_Price'])).abs().max()

6.821210263296962e-13

In [ ]:
df['Cost'].describe()

count    100000.000000
mean        314.614493
std         234.901995
min          10.002024
25%         125.467072
50%         252.801900
75%         462.376451
max         999.985219
Name: Cost, dtype: float64

In [ ]:
df['Margin'].describe()

count    100000.000000
mean         78.736857
std          74.236348
min           0.556870
25%          24.448402
50%          53.552720
75%         110.075103
max         447.207497
Name: Margin, dtype: float64

In [ ]:
df['Margin_%'].describe()

count    100000.000000
mean          0.193368
std           0.075143
min           0.047621
25%           0.131251
50%           0.200287
75%           0.259151
max           0.310343
Name: Margin_%, dtype: float64

In [ ]:
df['Stock_On_Hand'].describe()

count    100000.000000
mean        274.156670
std         129.853861
min          50.000000
25%         161.000000
50%         274.000000
75%         387.000000
max         499.000000
Name: Stock_On_Hand, dtype: float64

In [ ]:
df['Reorder_Level'].describe()

count    100000.000000
mean         49.467710
std          17.305614
min          20.000000
25%          34.000000
50%          50.000000
75%          64.000000
max          79.000000
Name: Reorder_Level, dtype: float64

In [ ]:
df['Lead_Time_Days'].describe()

count    100000.000000
mean          8.516810
std           3.458274
min           3.000000
25%           6.000000
50%           9.000000
75%          12.000000
max          14.000000
Name: Lead_Time_Days, dtype: float64

In [ ]:
df['Loyalty_Flag'].value_counts()

Loyalty_Flag
0    70280
1    29720
Name: count, dtype: int64

In [ ]:
(df['Cost'] - (df['Units'] * df['Cost_Price'])).abs().max()

4.547473508864641e-13

In [ ]:
(df['Margin'] - (df['Revenue'] - df['Cost'])).abs().max()

3.979039320256561e-13

In [ ]:
(df['Margin_%'] - (df['Margin'] / df['Revenue'])).abs().max()

2.220446049250313e-16

In [ ]:
df.isnull().sum()

Invoice_ID             0
Invoice_Date           0
City                   0
Store_Format           0
Category               0
Brand                  0
Channel                0
Payment_Mode           0
Units                  0
Cost_Price             0
Selling_Price          0
Revenue                0
Cost                   0
Margin                 0
Margin_%               0
Stock_On_Hand          0
Reorder_Level          0
Lead_Time_Days         0
Customer_Age       40081
Customer_Gender        0
Loyalty_Flag           0
dtype: int64

In [ ]:
df.to_csv('/content/Clean_FMCG_Data.csv', index=False)